opencode scripts (5)
docs/testing/test_scenario/scenario_qcvmt_show_queue/settings.py
docs/testing/test_scenario/scenario_qcvmt_show_queue/test_data.json
docs/testing/test_scenario/scenario_qcvmt_show_queue/conftest.py
docs/testing/test_scenario/scenario_qcvmt_show_queue/test_login.py
docs/testing/test_scenario/scenario_qcvmt_show_queue/test_qc_terminal_monitor.py